// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtzvuiltqqajgyzzdcal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0enZ1aWx0cXFhamd5enpkY2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYxMzg4NjYsImV4cCI6MjA0MTcxNDg2Nn0.R0gjrIQ4dRvauiKuuOIALd3HtsjOLC3yAk6WyN1teys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);